Ls 4 added decorative animation effect, created mobile menu
lyukhymchak/hys_academy pull request #5
Opened 2022-09-30 15:35 UTC by lyukhymchak

2022-10-09 10:53 UTC, philippbulanin requested changes

2022-10-09 10:53 UTC, philippbulanin commented on html_css/css/style.css
> +}
Please add blank lines beetwen all code blocks

2022-10-09 10:53 UTC, philippbulanin commented on html_css/css/style.css
> +  border-bottom: 1px solid #3d7fff20;
Please use variarle for color

2022-10-09 10:53 UTC, philippbulanin commented on html_css/index.html
> +              <!-- <button class="btn-slider">
Please remove commented code

2022-10-09 10:53 UTC, philippbulanin commented on html_css/index.html
> +              <!-- <button class="btn-slider">
Please remove commented code

2022-10-09 10:53 UTC, philippbulanin commented on html_css/index.html
> +              <!-- <button class="btn-slider">
Please remove commented code

2022-10-09 10:53 UTC, philippbulanin commented on html_css/js/mobile-menu.js
> +let hamburger = document.getElementsByClassName("hamburger-menu-logo")[0];
Use const for static variables

2022-10-09 10:53 UTC, philippbulanin commented on html_css/js/mobile-menu.js
> +console.log(hamburger);
Remove console log

2022-10-09 10:53 UTC, philippbulanin commented on html_css/js/mobile-menu.js
> +    let navbar = document.getElementsByClassName("navbar")[0];
Use const for static variables

2022-10-09 10:53 UTC, philippbulanin commented on html_css/js/mobile-menu.js
> +    console.log(navbar);
Remove console log

2022-10-09 10:53 UTC, philippbulanin commented on html_css/js/mobile-menu.js
> +    let closeBtn = document.getElementsByClassName("close-svg")[0];
Use const for static variables

2022-10-09 10:53 UTC, philippbulanin commented on html_css/js/mobile-menu.js
> +    closeBtn.onclick = function () {
Please mention, that in this case you creating new listener on every menu opening. You should avoid it

2022-10-17 08:08 UTC, lyukhymchak commented
@philippbulanin 
Issues have been fixed.

2022-11-02 19:33 UTC, merged